### ISSUE TITLE
The updater is a security risk. Please remove

### ISSUE THREAD

**Issue by solonovamax** [ReflxctionDev/NameModifier#5]
The updater is a security risk.
Downloading and executing arbitrary jars is something a mod should NEVER do.
Anyone could theoretically publish arbitrary malicious code.

**Comment by LowSpecCorgi** [comment]
Could you please clarify?

Since the updater downloads from the releases tab from this repository, which are theoretically 'vetted' by the owner of the repository, to avoid 'bad' stuff from happening.

Or are you against updaters in general?

**Comment by solonovamax** [comment]
Well, the thing is, who is to say that the developer can be 100% trusted?

Theoretically, they could release a new version with malicious code which hasn't been vetted by anyone (or even published for that matter), and then it would be pushed to all the users.
Additionally, if a breaking change was published in such a mod, then it might break everyone's games.
The best alternative would be to simply provide a link to the download page, allowing users to download it themselves.

**Comment by Revxrsal** [comment]
I can guarantee that this mod has terrible coding practices, respecting the fact that it was written around 2 or 3 years ago, and your point is completely valid. Since this mod is no longer being really maintained I don't think there will be any updates to trigger the whatever sort of "updater" we have here haha.
